[package]
name = "engine_json"
version = "0.6.0"
authors = ["<neohex262@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
calki-crypto = { path = "../../share_libs/crypto" }
util = {path = "../../share_libs/util"}
