[package]
name = "consensus_tendermint"
version = "0.1.0"


[dependencies]
dotenv = "0.10.0"
threadpool = "1.7.0"
serde = "1.0"
serde_derive = "1.0"
bincode = "0.8.0"
libproto = {path = "../../share_libs/proto"}
util = {path = "../../share_libs/util"}
rustc-serialize = "0.3"
protobuf = { version = "^1.0.0" }
log = "0.3"
clap = "2"
pubsub = { path = "../../share_libs/pubsub" }
calki-crypto = { path = "../../share_libs/crypto" }
proof = { path = "../proof" }
time = "0.1.36"
engine_json = { path = "../json" }
engine = { path = "../engine" }
lru-cache = "0.1"
logger = { path = "../../share_libs/logger" }
core = { path = "../../chain/core" }
cpuprofiler = "0.0.3"
authority_manage = { path = "../authority_manage" }
rustc-hex = "1.0"
