[package]
description = "Ethcore IO library"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-io"
version = "1.8.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
mio = "0.6.8"
crossbeam = "0.2"
parking_lot = "0.4"
log = "0.3"
slab = "0.2"

