[package]
name = "rlp_derive"
version = "0.1.0"
authors = ["<deathblow9@gmail.com>"]

[lib]
name = "rlp_derive"
proc-macro = true

[dependencies]
syn = "0.11.11"
quote = "0.3.15"

[dev-dependencies]
rlp = { path = "../rlp" }
