FROM ubuntu:16.04

COPY *.sh /tmp/
RUN /tmp/install_runtime.sh                     \
	&& rm -rf /var/lib/apt/lists                \
    && rm -rf ~/.cache/pip

WORKDIR /calki
ENV PATH $PATH:/calki/bin
CMD /bin/bash
