[package]
name = "authority_manage"
version = "0.1.0"
authors = ["<neohex262@gmail.com>"]

[dependencies]
serde = "1.0"
bincode = "0.8.0"
serde_json = "1.0"
serde_derive = "1.0"
util = {path = "../../share_libs/util"}
